services:
  # --- SPEECH TO TEXT (The Ears) ---
  whisper:
    image: rhasspy/wyoming-whisper
    container_name: billy_ears
    # command options: 
    # --model medium-int8 (Good balance of speed/accuracy)
    # --language en (Forces English for speed)
    command: --model medium-int8 --language en
    volumes:
      - ./wyoming:/data
    ports:
      - "10300:10300"
    restart: unless-stopped

  # --- TEXT TO SPEECH (The Voice) ---
  piper:
    image: rhasspy/wyoming-piper
    container_name: billy_voice
    # command options:
    # --voice en_US-lessac-medium (Standard generic voice)
    # We can change this to a funnier voice later!
    command: --voice en_US-lessac-medium
    volumes:
      - ./wyoming:/data
    ports:
      - "10200:10200"
    restart: unless-stopped
  openwakeword:
    image: rhasspy/wyoming-openwakeword
    container_name: billy_wake
    command: --custom-model-dir /custom --preload-model 'hey_billy'
    volumes:
      - ./wyoming:/data
      - ./wakeWords/en/hey_billy:/custom
    ports:
      - "10400:10400" 
    restart: unless-stopped
